updated stack status command

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,41 +11,58 @@ commands:
           name: Check stack status
           when: on_fail
           command: |
-            STACK_STATUS1=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-cloudfront-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
-            STACK_STATUS2=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-frontend-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
-            STACK_STATUS3=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-mgt-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
-            STACK_STATUS4=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-nodegroup-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
-            STACK_STATUS5=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-cluster-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
-            STACK_STATUS6=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-network-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
+            if aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-cloudfront-<<parameters.workflow_id>> >/dev/null 2>&1; then
+              STACK_STATUS1=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-cloudfront-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
 
-            if [ "$STACK_STATUS1" != "CREATE_COMPLETE" ]; then
-              echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-cloudfront-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
-              exit 1
+              if [ "$STACK_STATUS1" != "CREATE_COMPLETE" ]; then
+                echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-cloudfront-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
+                exit 1
+              fi
             fi
 
-            if [ "$STACK_STATUS2" != "CREATE_COMPLETE" ]; then
-              echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-frontend-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
-              exit 1
+            if aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-frontend-<<parameters.workflow_id>> >/dev/null 2>&1; then
+              STACK_STATUS2=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-frontend-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
+
+              if [ "$STACK_STATUS2" != "CREATE_COMPLETE" ]; then
+                echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-frontend-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
+                exit 1
+              fi
             fi
 
-            if [ "$STACK_STATUS3" != "CREATE_COMPLETE" ]; then
-              echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-mgt-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
-              exit 1
+            if aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-mgt-<<parameters.workflow_id>> >/dev/null 2>&1; then
+              STACK_STATUS3=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-mgt-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
+
+              if [ "$STACK_STATUS3" != "CREATE_COMPLETE" ]; then
+                echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-mgt-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
+                exit 1
+              fi
             fi
 
-            if [ "$STACK_STATUS4" != "CREATE_COMPLETE" ]; then
-              echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-nodegroup-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
-              exit 1
+            if aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-nodegroup-<<parameters.workflow_id>> >/dev/null 2>&1; then
+              STACK_STATUS4=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-nodegroup-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
+
+              if [ "$STACK_STATUS4" != "CREATE_COMPLETE" ]; then
+                echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-nodegroup-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
+                exit 1
+              fi
             fi
 
-            if [ "$STACK_STATUS5" != "CREATE_COMPLETE" ]; then
-              echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-cluster-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
-              exit 1
+            if aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-cluster-<<parameters.workflow_id>> >/dev/null 2>&1; then
+              STACK_STATUS5=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-cluster-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
+
+              if [ "$STACK_STATUS5" != "CREATE_COMPLETE" ]; then
+                echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-cluster-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
+                exit 1
+              fi
             fi
 
-            if [ "$STACK_STATUS6" != "CREATE_COMPLETE" ]; then
-              echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-network-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
-              exit 1
+            if aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-network-<<parameters.workflow_id>> >/dev/null 2>&1; then
+              STACK_STATUS6=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-network-<<parameters.workflow_id>> --query 'Stacks[].StackStatus' --output text)
+
+              if [ "$STACK_STATUS6" != "CREATE_COMPLETE" ]; then
+                echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name ${ENVIRONMENT_NAME}-eks-network-<<parameters.workflow_id>> --query 'Stacks[].StackStatusReason' --output text)"
+                exit 1
+              fi
             fi
   destroy-environment:
     description: Destroy cloudformation stacks given a workflow ID.
