updated stack status command

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,22 @@
 version: 2.1
 
 commands:
+  check-stack-status:
+    description: Check cloudformation stack status given a stackname.
+    parameters:
+      stack_name:
+        type: string
+    steps:
+      - run:
+          name: Check stack status
+          when: on_fail
+          command: |
+            STACK_STATUS=$(aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name <<parameters.stack_name>> --query 'Stacks[].StackStatus' --output text)
+            if [ "$STACK_STATUS" != "CREATE_COMPLETE" ]; then
+              echo "Stack creation failed. Reason: $(aws cloudformation describe-stacks ${AWS_DEFAULT_REGION} --stack-name <<parameters.stack_name>> --query 'Stacks[].StackStatusReason' --output text)"
+              exit 1
+            fi
+
   destroy-environment:
     description: Destroy cloudformation stacks given a workflow ID.
     parameters:
@@ -116,6 +132,8 @@ jobs:
               --region ${AWS_DEFAULT_REGION} \
               --parameter-overrides file://.circleci/files/parameters/network.json  \
               --tags project=${ENVIRONMENT_NAME}
+      - check-stack-status:
+          stack_name: "${ENVIRONMENT_NAME}-eks-network-${CIRCLE_WORKFLOW_ID:0:7}"
       - run:
           name: Ensure EKS Cluster exists
           command: |
@@ -127,6 +145,8 @@ jobs:
               --parameter-overrides file://.circleci/files/parameters/cluster.json \
               --capabilities CAPABILITY_NAMED_IAM
           no_output_timeout: 15m
+      - check-stack-status:
+          stack_name: "${ENVIRONMENT_NAME}-eks-cluster-${CIRCLE_WORKFLOW_ID:0:7}"
       - run:
           name: Ensure Nodegroup exists
           command: |
@@ -137,6 +157,9 @@ jobs:
               --region ${AWS_DEFAULT_REGION} \
               --parameter-overrides file://.circleci/files/parameters/eks-nodegroup.json \
               --capabilities CAPABILITY_NAMED_IAM
+          no_output_timeout: 15m
+      - check-stack-status:
+          stack_name: "${ENVIRONMENT_NAME}-eks-nodegroup-${CIRCLE_WORKFLOW_ID:0:7}"   
       - run:
           name: Ensure eks instances exists
 
@@ -149,6 +172,9 @@ jobs:
               --parameter-overrides file://.circleci/files/parameters/eks-mgt.json
               --output text >> .circleci/outputs/check-deployed.txt
             cat .circleci/outputs/check-deployed.txt
+          no_output_timeout: 15m
+      - check-stack-status:
+          stack_name: "${ENVIRONMENT_NAME}-eks-mgt-${CIRCLE_WORKFLOW_ID:0:7}"
       - run:
           name: Extract the IPs of the all instances for Ansible
           command: |
@@ -169,6 +195,9 @@ jobs:
               --region ${AWS_DEFAULT_REGION} \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
               --tags project=${ENVIRONMENT_NAME}
+          no_output_timeout: 15m
+      - check-stack-status:
+          stack_name: "${ENVIRONMENT_NAME}-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
       - run: yum -y install tar gzip
       - persist_to_workspace:
           root: ~/
@@ -271,6 +300,9 @@ jobs:
               --region ${AWS_DEFAULT_REGION} \
               --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
               --tags project=${ENVIRONMENT_NAME}
+          no_output_timeout: 15m
+      - check-stack-status:
+          stack_name: "${ENVIRONMENT_NAME}-cloudfront-${CIRCLE_WORKFLOW_ID:0:7}"
       - run: yum -y install tar gzip
       - destroy-environment:
           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
